#!/usr/bin/env bash
# Build a harness that runs lifted functions for one image.
#
# Usage: ./scripts/build-lifted-harness.sh IMAGE [LIFT_ROOT] [OUT_DIR]
#
#   IMAGE       the PE32+ image the lifted functions came from
#   LIFT_ROOT   where lift manifests live (default work/linux64/lift)
#   OUT_DIR     where to put the harness (default work/linux64/bin)
#
# Only manifests whose recorded image hash matches the image are used: lifting
# function A from one build of a binary and function B from another and then
# running them together would be a silent correctness hole.
#
# Requires: the Remill install under .deps/src/remill/install (see ROADMAP P2),
# clang, and the lift manifests produced by `python -m tools.linux64 lift`.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
IMAGE="${1:-}"
LIFT_ROOT="${2:-$ROOT/work/linux64/lift}"
OUT_DIR="${3:-$ROOT/work/linux64/bin}"
REMILL_INSTALL="$ROOT/.deps/src/remill/install"
CXX="${CXX:-clang++}"
CC="${CC:-clang}"
CXXFLAGS="${CXXFLAGS:--O1 -g -std=c++20 -Wall -Wextra}"

if [[ -z "$IMAGE" ]]; then
  echo "usage: $0 IMAGE [LIFT_ROOT] [OUT_DIR]" >&2
  exit 2
fi
if [[ ! -f "$IMAGE" ]]; then
  echo "no such image: $IMAGE" >&2
  exit 2
fi
if [[ ! -d "$REMILL_INSTALL/include/remill" ]]; then
  echo "missing Remill install at $REMILL_INSTALL (build it: .deps/src/remill, see ROADMAP P2)" >&2
  exit 1
fi

mkdir -p "$OUT_DIR"
WORK="$OUT_DIR/$(basename "$IMAGE" | tr '.' '_').build"
mkdir -p "$WORK"

# --- pick the manifests that belong to this exact image --------------------

python3 - "$IMAGE" "$LIFT_ROOT" "$WORK/lifted_symbols.inc" "$WORK/lifted.ll.list" <<'PY'
import hashlib, json, pathlib, re, sys

image_path, lift_root, inc_path, list_path = sys.argv[1:5]
digest = hashlib.sha256(pathlib.Path(image_path).read_bytes()).hexdigest()

entries, ir_paths = [], []
for manifest_path in sorted(pathlib.Path(lift_root).glob("*/*.manifest.json")):
    manifest = json.loads(manifest_path.read_text())
    source = manifest.get("source", {})
    if source.get("image_sha256") != digest:
        continue
    ir = manifest_path.parent / manifest["artifact"]["ir"].split("/")[-1]
    if not ir.exists():
        ir = manifest_path.parent / pathlib.Path(manifest["artifact"]["ir"]).name
    text = ir.read_text()
    match = re.search(r"^define [^\n]*@([A-Za-z_][A-Za-z0-9_.$]*)\(ptr noalias %state",
                      text, re.M)
    if not match:
        match = re.search(r"^define [^\n]*@([A-Za-z_][A-Za-z0-9_.$]*)\(", text, re.M)
    if not match:
        raise SystemExit(f"{ir}: no lifted function found")
    entries.append((source["function_va"], match.group(1), ir.name))
    ir_paths.append(str(ir))

if not entries:
    raise SystemExit(f"no lift manifests match {image_path} (sha256 {digest[:16]}...)")

seen = {}
for va, symbol, ir_name in entries:
    if va in seen:
        raise SystemExit(f"two manifests claim {va:#x}: {seen[va]} and {symbol}")
    seen[va] = symbol

with open(inc_path, "w") as handle:
    handle.write("/* generated by scripts/build-lifted-harness.sh */\n")
    for _va, symbol, _ir in entries:
        handle.write(f'extern "C" Memory *{symbol}(State *, uint64_t, Memory *);\n')
    handle.write("static const LiftedEntry kLiftedEntries[] = {\n")
    for va, symbol, _ir in entries:
        handle.write(f'    {{ {hex(va)}, (lifted_function)&{symbol}, "{symbol}" }},\n')
    handle.write("};\n")
with open(list_path, "w") as handle:
    handle.write("\n".join(ir_paths) + "\n")
print(f"lifted functions for {image_path}: {len(entries)}")
for va, symbol, _ir in entries:
    print(f"  {va:#x} {symbol}")
PY

# --- compile the lifted IR and the harness ---------------------------------

mapfile -t IR_FILES < "$WORK/lifted.ll.list"
OBJECTS=()
for ir in "${IR_FILES[@]}"; do
  object="$WORK/$(basename "$ir" .ll).o"
  # The IR carries the guest's target triple (windows). We compile it for the
  # host on purpose: the data layout is identical between win64 and linux x86-64,
  # and the point of the project is native Linux code.
  # shellcheck disable=SC2086
  "$CC" -c -O1 -g -Wno-override-module -o "$object" "$ir"
  OBJECTS+=("$object")
done

# shellcheck disable=SC2086
"$CXX" $CXXFLAGS -I"$ROOT/runtime/linux64" -I"$REMILL_INSTALL/include" \
  -I"$WORK" -c -o "$WORK/lifted_runtime.o" "$ROOT/runtime/linux64/lifted_runtime.cpp"
# shellcheck disable=SC2086
"$CXX" $CXXFLAGS -I"$ROOT/runtime/linux64" -I"$REMILL_INSTALL/include" \
  -I"$WORK" -c -o "$WORK/lifted_harness.o" "$ROOT/runtime/linux64/lifted_harness.cpp"
# shellcheck disable=SC2086
"$CC" -O1 -g -c -o "$WORK/image_pe64.o" "$ROOT/runtime/linux64/image_pe64.c"

HARNESS="$OUT_DIR/lifted_harness"
# shellcheck disable=SC2086
"$CXX" -O1 -g -o "$HARNESS" "$WORK/lifted_harness.o" "$WORK/lifted_runtime.o" \
  "$WORK/image_pe64.o" "${OBJECTS[@]}"

echo "built: $HARNESS"
